### ISSUE TITLE
Bug in 1.0.1 - "Non-Image content-type returned"

### ISSUE THREAD

**Issue by webbertakken** [ruairidhwm/action-cats#11]
As can be seen in this [comment](https://github.com/Unity-CI/docker/pull/38#issuecomment-718255731) generated by action-cats, the image is posted correctly, but it's not showing up. When clicking the link the message `Non-Image content-type returned` [appears](https://camo.githubusercontent.com/0d6ee1308ff51bca519ea2885d4c7f63176ed9ec/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f56626e5551706e6968505349674958755a762f67697068792e676966).

**Comment by ruairidhwm** [comment]
Hey @webbertakken, thanks for the report! Looks like a bit of a strange one. This error normally occurs when the link isn't directly to the media, but to the page containing it. In our constants, however, we directly link to the GIF each time:

https://github.com/ruairidhwm/action-cats/blob/master/src/constants/catGifs.ts

**Comment by webbertakken** [comment]
Looks like it actually uploads the image as a blob, and the connection didn't work or something happened. 

Also note that that was the first of your action in that repository.

Either way, there's nothing I can do from my side.

**Comment by ruairidhwm** [comment]
Hey,

Yeah looks like that's the issue. I'll close this but let me know if you keep having problems and I'll come up with another way of inserting the gif :)

**Comment by webbertakken** [comment]
I've implemented the latest version in another repository and it worked when implementing and running for the first time (pre-merge).

Then the second run (first PR opened after merging the workflow to `main`) showed me a [broken](https://github.com/Unity-CI/Website/pull/53#issuecomment-727275576) image again. 

In the other repository I have not seen it again so far.

**Comment by ruairidhwm** [comment]
I wonder if it's something to do with how GitHub process a repeat image? Perhaps they're invalidating the address in a cache, or marking it as spam somewhere.

**Comment by webbertakken** [comment]
I'm not completely sure. I vote to reopen the issue as it does not seem to be resolved.

Note that there is also an unresolved promise rejection ([here](https://github.com/Unity-CI/docker/pull/47/checks?check_run_id=1405964478)).

**Comment by webbertakken** [comment]
Found another occurrence where it [didn't](https://github.com/Unity-CI/Website/pull/54#issuecomment-728360130) work properly. Looks like this action needs a bit of work still.

**Comment by ruairidhwm** [comment]
Thanks for the heads up. When I get some time free from work, I'll look to improving it.

**Comment by webbertakken** [comment]
Looks to be happening about 25 to 50% of the time. Here's another [example](https://github.com/game-ci/docker/pull/67#issuecomment-765436535). Will you be maintaining the action and do you have any angle on how to fix it?

Perhaps I could help out if you help point me in the right direction.

**Comment by ruairidhwm** [comment]
I will be maintaining the action, but don't check super frequently as I'm pretty busy with work.

I think a potential fix would be to host a selection of gifs within the repo as assets and call those, rather than linking directly to giphy. That may avoid the connection issue.

**Comment by webbertakken** [comment]
Understandable of course. Happy to hear you intend on maintaining it!

I agree GitHub-hosted might make a lot of sense. I also like the idea of having the images in the repository.

**Comment by ruairidhwm** [comment]
@webbertakken - I've updated the action now so we're hosting the gifs as assets on the repo. So far it looks like it's working ok, but I'll leave this issue open in case you run into the same problem.

**Comment by rYuuk** [comment]
It seems this issue is still happening. 
![image](https://user-images.githubusercontent.com/1121080/146762632-fda4e8f6-442a-4165-87b3-7ad2bc999a95.png)

Open the gif in different tab gives `Non-Image content-type returned`

**Comment by webbertakken** [comment]
I can confirm, the issue was never completely solved.

**Comment by ruairidhwm** [comment]
Thanks, @rYuuk - this looks as though it _should_ be resolved with the smaller GIFs and an update I've made to link directly to the files. Closing again but please comment or open a new issue if you see anything.

**Comment by rYuuk** [comment]
![image](https://user-images.githubusercontent.com/1121080/147932883-621458fa-1ae9-44d5-8c24-72d3ebea597d.png)
@ruairidhwm Looks like it didn't worked.

**I did updated my github action version.** 
![image](https://user-images.githubusercontent.com/1121080/147933337-0abf609f-30ad-4c3c-820c-532a40068244.png)

**It seems it is still pointing to older version.** 
![image](https://user-images.githubusercontent.com/1121080/147933268-d54e1289-a814-446e-bfda-cf7641827b97.png)

**Comment by webbertakken** [comment]
As mentioned; the issue was never completely solved.

> Thanks, @rYuuk - this looks as though it _should_ be resolved with the smaller GIFs and an update I've made to link directly to the files. Closing again but please comment or open a new issue if you see anything.

One or two cats consistently work, but others consistently do not. 

Actually it looks like most of the cats don't work because the links don't point to the actual image. Even though it looks like they do as they end in a file extension.

**Steps to debug**

Here's what was posted by the bot

![image](https://user-images.githubusercontent.com/20756439/182464441-013b0079-48ab-45e8-b928-1ee4e31a47ae.png)

This is the result

![image](https://user-images.githubusercontent.com/20756439/182464557-1ce4667f-6221-49ca-9834-f214074dc2cf.png)

When switching between `Write` and `Preview` tab, you can see that the network request results in a 404.

![image](https://user-images.githubusercontent.com/20756439/182469343-17eea11a-5fb8-42cc-9cee-cbaa9daa67f8.png)

Note that this request is to a [github camo endpoint](https://camo.githubusercontent.com/9d3e0177e6f6e03e31d87642dab82d985f07a8799be58851b786e098eae433f1/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f56626e5551706e6968505349674958755a762f67697068792e676966)

Opening the link directly in your browser will show a 400 response with the following body

```text
Non-Image content-type returned
```

So it looks like the original url is not returning an image.

When opening the original url `https://media.giphy.com/media/VbnUQpnihPSIgIXuZv/giphy.gif` in the browser, we can observe that indeed no image is returned, but an entire page:

![image](https://user-images.githubusercontent.com/20756439/182470741-7b50020c-8f64-4205-8cc2-8381e13b1fe7.png)

**Conclusion**

Some images work fine, others don't point to a resource with an image type resulting in a failed response.

**Solution**

I'd recommend the following

- check the type of the response for each image listed and update the links accordingly
- create a test that checks this automatically and is run as part of a PR that runs against this repo to ensure integrity
- create a new release, bumping the version tag

**Comment by webbertakken** [comment]
~~And then I wanted to create PR to fix it and noticed my repo isn't referencing the latest version of action-cats yet 😅~~

Edit: problem persists even on v1.0.2
